name: My first workflow

on: push
#check
jobs: 
    first_job:
      runs-on: ubuntu-latest
      steps:
        - name: welcome message
          run: echo "My first Github Actions job"
          
        - name: List files
          run: ls
        - name: read file
          run: cat README.md